In [1]:
import numpy as np
def floyd_warshall(graph):
    num_vertices = len(graph)
    distance = np.copy(graph)
    for k in range(num_vertices):
        for i in range(num_vertices):
            for j in range(num_vertices):
                if distance[i][j] > distance[i][k] + distance[k][j]:
                    distance[i][j] = distance[i][k] + distance[k][j]
    return distance
graph = [
    [0, 1, np.inf],
    [1, 0, 2],
    [np.inf, 2, 0]
]

shortest_paths = floyd_warshall(graph)
print("Shortest path distance matrix:")
print(shortest_paths)

Shortest path distance matrix:
[[0. 1. 3.]
 [1. 0. 2.]
 [3. 2. 0.]]
